credentials:
  usernames:
    elbrus:
      email: any@any.any
      name: User
      password: $2b$12$Od3lRLc9yzgLq/PyDXpZwOzPmcTMg3IAd0rhlhfQgxwWpDkRk5dc.
cookie:
  expiry_days: 90
  key: "elbrus"
  name: elbrus
preauthorized:
  emails:
  - any@any.any